### ISSUE TITLE
Deconvolution problem

### ISSUE THREAD

**Issue by wl-stepp** [LEB-EPFL/iSIM#12]
Some of this is a conversation copied over from Slack.

We where trying to deconvolute my iSIM data with Juan and we got this two errors
```
DECON SHAPE  (60, 1, 1, 2048, 2048)
-231026_TMRE_SybrGOLD_U2OS__12_MMStack_Pos0.ome.tif
//lebnas1/microsc125/iSIMstorage/Users/Josefa/231026_TMRE_SybrGOLD_U2OS/-231026_TMRE_SybrGOLD_U2OS__12/-231026_TMRE_SybrGOLD_U2OS__12_MMStack_Pos0.ome.tif
<tifffile.TiffFile '-231026_TMRE_Sy…ack_Pos0.ome.tif'> OME series expected 2 frames, got 1
Traceback (most recent call last):
  File "c:\Internal\deconvolution\script_juan.py", line 34, in <module>
    cuda_decon.decon_ome_stack([file.as](http://file.as/)_posix(), params=parameters)
  File "c:\Internal\deconvolution\cuda_decon.py", line 141, in decon_ome_stack
    data = tif.asarray()
  File "C:\Internal\.envs\decon_310\lib\site-packages\tifffile\tifffile.py", line 4095, in asarray
    result = self.filehandle.read_array(
  File "C:\Internal\.envs\decon_310\lib\site-packages\tifffile\tifffile.py", line 13363, in read_array
    raise ValueError(f'failed to read {nbytes} bytes, got {n}')
ValueError: failed to read 16777216 bytes, got 8409566
[14:37] DECON SHAPE  (1, 1, 1, 2048, 2048)
Traceback (most recent call last):
  File "c:\Internal\deconvolution\script_juan.py", line 34, in <module>
    cuda_decon.decon_ome_stack([file.as](http://file.as/)_posix(), params=parameters)
  File "c:\Internal\deconvolution\cuda_decon.py", line 282, in decon_ome_stack
    frame_tiffdata['UUID']['@FileName'] = os.path.basename(out_file)
TypeError: string indices must be integers
```

This is the folder with the files we where trying to run
![image (1)](https://github.com/LEB-EPFL/iSIM/assets/52414717/51cc4ed5-cd81-4282-b224-d3f05767bd77)

**Comment by wl-stepp** [comment]
Just to add some context, the algorithm seems to crash with two separate errors (second one appeared when we removed the first problematic file):
TypeError: string indices must be integers
ValueError: failed to read 16777216 bytes, got 8409566
Likely there's some problem in reading in the names with the "-" before, and the second one might be related to corrupted metadata, but I suggested asking you before spending too much time troubleshooting just in case you've experienced this before

**Comment by wl-stepp** [comment]
231026_TMRE_SybrGOLD_U2OS__12 is just one frame, so I'm thinking that acquisition was aborted? The program is trying to read the second channel which is not there.
Is this one frame important? We could try to resave it and try again.

**Comment by wl-stepp** [comment]
Problem 2 was a problem with single frames for deconvolution. Fixed by
https://github.com/LEB-EPFL/iSIM/commit/579bd2a684d82ed664049a87ddeac3c776dbd3a4
